# Generated by Django 4.2.2 on 2023-06-22 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bootcamp13", "0002_course_alter_bootcampmembers_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="name",
            new_name="courseName",
        ),
    ]
